### ISSUE TITLE
Customize the SQL generation for DB2 queries?

### ISSUE THREAD

**Issue by gtas-verisk** [Yoinbol/MicroOrm.Pocos.SqlGenerator#11]
Thank you for the awesome work :-) I used this before with SQL Server and worked great in combination with Dapper, I'm trying to figure out if I can make this work with DB2, any suggestions tapping on the generated SQL and make some modifications?

Thanks.

**Comment by gtas-verisk** [comment]
Yeah, I think I got this, I'll just implement ISqlGenerator and change your implementation from SqlGenerator.

**Comment by ElNinjaGaiden** [comment]
Great! Yeah that's the way to override the generation of the queries
