### ISSUE TITLE
Get rows where column value is null

### ISSUE THREAD

**Issue by Shawson** [Yoinbol/MicroOrm.Pocos.SqlGenerator#5]
Hi,

Looks like I can't query values based on a column value being null- I have a table with a nullable datetime column which indicated if a row is disabled- the sql generated is;

exec sp_executesql N'SELECT [tblChecksToPerform].[CheckId], [tblChecksToPerform].[CheckTypeId], [tblChecksToPerform].[SystemName], [tblChecksToPerform].[Settings], [tblChecksToPerform].[Outcomes], [tblChecksToPerform].[CheckSuiteId], [tblChecksToPerform].[Disabled] FROM [dbo].[tblChecksToPerform] WITH (NOLOCK) WHERE [tblChecksToPerform].[Disabled] = @Disabled ',N'@Disabled datetime',@Disabled=NULL
go

I'd guess this needs to check for a null value and alter the where to be WHERE [tblChecksToPerform].[Disabled] is null

Any thoughts- I'm happy to do a Pull but wondered what people thought?

**Comment by Yoinbol** [comment]
Hi. Nice find.
Yeah, do the pull if you don't mind 😀
On Mar 31, 2016 3:30 AM, Shawson <notifications@github.com> wrote:Hi,

Looks like I can't query values based on a column value being null- I have a table with a nullable datetime column which indicated if a row is disabled- the sql generated is;

exec sp_executesql N'SELECT [tblChecksToPerform].[CheckId], [tblChecksToPerform].[CheckTypeId], [tblChecksToPerform].[SystemName], [tblChecksToPerform].[Settings], [tblChecksToPerform].[Outcomes], [tblChecksToPerform].[CheckSuiteId], [tblChecksToPerform].[Disabled] FROM [dbo].[tblChecksToPerform] WITH (NOLOCK) WHERE [tblChecksToPerform].[Disabled] = @Disabled ',N'@Disabled datetime',@Disabled=NULL
go

I'd guess this needs to check for a null value and alter the where to be WHERE [tblChecksToPerform].[Disabled] is null

Any thoughts- I'm happy to do a Pull but wondered what people thought?

**Comment by ElNinjaGaiden** [comment]
@Shawson both PR where merged and the package was updated to nuget. Thanks!
