### ISSUE TITLE
SQLGenerator ToWhere method scope

### ISSUE THREAD

**Issue by Rastas** [Yoinbol/MicroOrm.Pocos.SqlGenerator#9]
Hi Guys, great library, I just have one favour please. I sometimes need to extend and override the GetSelect method on the SQLGenerator to enable me to create custom SQL statements. The problem is that when I do that, I cant refer to the "ToWhere" method in the base class because it is private. Any chance of changing its scope to protected? Alternatively, if I'm using it wrong, please let me know of the correct way. I have attached an example SQLGenerator extension class as I use it
[CustomSQLGenerator.txt](https://github.com/Yoinbol/MicroOrm.Pocos.SqlGenerator/files/347305/CustomSQLGenerator.txt)

cheers

**Comment by ElNinjaGaiden** [comment]
Released on v1.0.0.4
Thanks
